#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# Load global styles, colors and icons
source "$CONFIG_DIR/globalstyles.sh"

POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"
POPUP_OFF="sketchybar --set \$NAME popup.drawing=off"

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

sketchybar --bar "${bar[@]}" --default "${item_defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
# source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/spacer.sh" 1 left
source "$ITEM_DIR/spaces_simple.sh"

# source "$ITEM_DIR/spacer.sh" 3 left

source "$ITEM_DIR/current_window.sh"
# Notch

# Right
# source "$ITEM_DIR/control_center.sh"
source "$ITEM_DIR/datetime.sh"
source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/dnd.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
# source "$ITEM_DIR/diskmonitor.sh"

# source "$ITEM_DIR/spacer.sh" 2 right
#
# source "$ITEM_DIR/brew.sh" right
# source "$ITEM_DIR/reminders.sh" right
# source "$ITEM_DIR/messages.sh" right
# source "$ITEM_DIR/mail.sh" right
# source "$ITEM_DIR/weather.sh" right

source "$ITEM_DIR/music.sh" right

# Brackets '/space\..*/'
sketchybar --add bracket left.side '/space\..*/' \
	--set left.side "${bracket_defaults[@]}" \
	--add bracket status_icons volume_icon volume wifi date clock charging_icon battery \
	--set status_icons "${bracket_defaults[@]}"
# --add bracket notifications weather aqi reminders messages mail brew                   \
# --set notifications "${bracket_defaults[@]}"                                          \

sketchybar --hotload on
sketchybar --update
