-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
	hl.dsp.focus({ workspace = "1" })
	hl.exec_cmd(browser)
	hl.dsp.focus({ workspace = "2" })
	hl.exec_cmd(terminal)
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd(plugins)
	hl.exec_cmd(statusbar)
end)
